% deletes all temporary files in the tests directory

clean

cases = [ ...
   'free           '; ...
   'VolAtt         '; ...
   'halfspace      '; ...
   'calib          '; ...
   'Munk           '; ...
   'MunkLeaky      '; ...
   'MunkRot        '; ...
   'sduct          '; ...
   'Dickins        '; ...
%   'Dickins/March  '; ...  need to cd up two levels with this
%   'Dickins/Precalc'; ...
   'arctic         '; ...
   'SBCX           '; ...
   'BeamPattern    '; ...
   'TabRefCoef     '; ...
   'PointLine      '; ...
   'ParaBot        '; ...
   'Ellipse        '; ...
   'terrain        '; ...
   '3DAtlantic     '; ...
   'TLslices       '; ...
   'head           '; ...
   'wedge          '; ...
   'Gulf           '; ...
   'block          '; ...
   'PekerisRD      '; ...
   'noise          '; ...
   'BroadBand      '; ...
   'SedAtten       '; ...
   'step           '; ...
   'Bellhop3DTests '; ...
   ];

for icase = 1 : size( cases, 1 )
   directory = deblank( cases( icase, : ) )
   eval( [ 'cd ' directory ] )
   clean
   
   fileExisting  = ( exist( fullfile( currentFolder, 'cleanall' ), 'file' ) == 2);
   if ( fileExisting ); cleanall; end
   
   cd ..
end

