
cases = [ 'free           '; ...
          'halfspace      '; ...
          'ParaBot        '; ...
          'HyperBot       '; ...
          'KoreanSeas     '; ...
          'Weymouth       '; ...
          'KermitRoosevelt'; ...
          'Munk           '; ...
          'MunkRot        '; ...
          'PenetrableWedge'; ...
          'Seamount       '; ...
          'DoubleSeamount '; ...
          'Taiwan         '; ...
          'TruncatedWedge '; ...
          'PerfectWedge   '; ...
              ];


for icase = 1: size( cases, 1 )
    directory = deblank( cases( icase, : ) )
    eval( [ 'cd ' directory ] );
    delete *.prt
    delete *.shd
    delete *.grn
    delete *.mod
    delete *.shd.mat
    delete *.arr
    delete *.asv
    delete *.rts
    delete *.ray
    delete *.irc
    delete *.brc
    delete ._*
    cd ..
end

