clear all
% Runs a battery of test problems for BELLHOP3D

cases = [ 'free           '; ...
          'LloydMirror    '; ...
          'halfspace      '; ...
          'ParaBot        '; ...
          'Munk           '; ...
          'MunkRot        '; ...
          'KoreanSeas     '; ...
          'Taiwan         '; ...
          'PerfectWedge   '; ...
          'PenetrableWedge'; ...
          'TruncatedWedge '; ...
          'Seamount       '; ...
          'DoubleSeamount '; ...
              ];

for icase = 1 : size( cases, 1 )
    directory = deblank( cases( icase, : ) )
    eval( [ 'cd ' directory ] );

    %eval( [ '! ' matlabroot '/bin/matlab -r runtests &' ] )
    runtests

    cd ..
end
